---
- name: "update local apt repo"
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "remove stale dependancies"
  become: true
  apt:
    autoremove: yes

- name: "install node and npm"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: "pm2"
    global: yes
    state: present
    production: yes

