---
- name: "update local apt repo"
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "remove stale dependancies"
  become: true
  apt:
    autoremove: yes

- name: "install node and npm"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: "pm2"
    global: yes
    state: present
    production: yes

- name: create backend directory
  file:
    path: ~/backend_app_dir
    state: directory

- name: "copy artefact to instance"
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend_app_dir/artifact.tar.gz


- name: "start app"
  become: true
  shell: |
    cd /home/ubuntu/backend_app_dir
    tar xzvf artifact.tar.gz
    npm install
    npm run build
    pm2 stop all
    pm2 start npm --start
